services:
  frontend:
    build:
      context: ./frontend/be-compliant
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=kontrollere
      - DB_USER=sondre
      - DB_PASSWORD=hein