ktor:
    application:
        modules:
            - no.bekk.ApplicationKt.module
    deployment:
        port: 8080

    database:
        url : "jdbc:postgresql://localhost:5432/kontrollere"
        user : "hein"
        password : "hein"
}