name: Assign PR Assignees

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - with:
          add-assignees: 'true'
          assignees: 'sondrekanstad, andersstandal, JakobNH'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
