name: Build and deploy frontend to SKIP
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'backend/**'

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}
  argo_version_file: api-version-frontend

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Set working directory
        run: echo "::set-env name=WORKING_DIR::./frontend/beCompliant"

      - name: Change directory for subsequent steps
        run: cd $WORKING_DIR

      - name: Run npm install and build
        run: |
          npm ci
          npm run test
          npm run build

      - name: Login to Github Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }}

      - name: Build Docker and push
        id: build
        uses: docker/build-push-action@f6010ea70151369b06f0194be1051fbbdff851b2 # v6.0.2
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos with Required Permissions
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@9ba014f232304231c670808ecaca97415d88c830 # v0.2.1
        with:
          image_url: ${{ needs.build.outputs.image_url }}

  argo:
    name: Update version in apps-repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apps-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: kartverket/skvis-apps
          ref: main
          token: ${{ secrets.ARGO_PAT }}
      - name: Update version
        run: |
          echo "\"${{ needs.build.outputs.image_url }}\"" > "env/atgcp1-dev/regelrett-main/${{ env.argo_version_file }}"
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "Regelrett CI"
          git commit -am "Update Regelrett frontend ${{ env.argo_version_file }}"
          git push